### PR TITLE
Parametrize key selection for the list task

### LINKED ISSUE #3778: Include database and schema fields into the list task json output
### Imporevement description
Update List Task JSON output (`dbt ls --output json`) to include `database` and `schema` fields. In the current released version (0.20.1),  both fields are available under the `config` field, but the `schema` disregards custom generated schema names (using macros), and the `database` field is always null.

After the update JSON output will look like below (irrelevant fields removed):
```
{
  "unique_id": "model.my_project.my_table",
  "name": "my_table",
  "database": "my_database",
  "schema": "stg-my_schema",  
  "alias": "my_table",
  "original_file_path": "models/my_table.sql",
  "config": {
    "alias": null,
    "schema": "my_schema",
    "database": null
  }
}
```

### Use case example 
This is useful for the promotion of objects from one environment to another. For example, my data pipelines look like this: 
1. Run DBT DAG with staging profile. The naming macro creates objects with some prefix 
2. Run tests on the stage data objects, if everything is good:
3. Promote objects to production. 
So, I need to know which objects were in the DAG, their names in the database, and how they should be named in the target environment. (`dbt ls --output json -t stg and `dbt ls --output json -t prd`)

### Implementation
I'm happy to contribute to the implementation of this improvement. I have implemented this locally, ran integration tests, and willing to create a pull request.

### PR DESCRIPTION
**Pull request by juma-adoreme**
resolves #3778 #3395 

Parametrize set of `ALLOWED_KEYS` in the list task by adding new flag `--output-keys`. 
Usage example: `dbt ls --model inner outer --output json --output-keys database,alias `

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by jtcohen6** [comment]
@juma-adoreme `flake8` just checks for code style. The only failure is [here](https://github.com/dbt-labs/dbt/pull/3838/checks?check_run_id=3473868291#step:5:14):
```
core/dbt/task/list.py:117:47: W291 trailing whitespace
```

**Comment by juma-adoreme** [comment]
@jtcohen6, thanks! I removed that whitespace and created a new commit. I also ran `make flake8` to check for any other code style issues and it passed without issues. 

Now I see that Integration Matrix Generation failed with the `MODULE_NOT_FOUND` error. I'm not sure why that happened. Let me know if there is anything I can do. Thanks!

**Comment by jtcohen6** [comment]
It looks like your branch is missing [this file](https://github.com/dbt-labs/dbt/blob/develop/.github/scripts/integration-test-matrix.js), which is causing the error in [the workflow](https://github.com/dbt-labs/dbt/runs/3482092155). Could you pull the latest changes from `develop`?

**Comment by juma-adoreme** [comment]
Thanks, I merged my branch with the origin develop branch, and that solved the issue with the missing file. I also added output_keys to the RPC List Parameters list and all integration tests passed at least in my local environment, so I have pushed the new commit.

**Review by jtcohen6 — APPROVED** [review]
@juma-adoreme This looks great! Thanks for thinking to add to the RPC task, and for adding the test.

I'm going to edit the changelog, just to move up the entry and add you to the list of contributors. Then this is good to merge :)

**Comment by juma-adoreme** [comment]
@jtcohen6 Thank you for accepting this change and for your guidance in the implementation!

**Pull request merged**
