### PR TITLE
PRODDOCS-991: convert test to data_test

### LINKED ISSUE #8698: [CT-3146] [Implementation] updating the unit-tests block (to start with test name instead of model)
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

From https://github.com/dbt-labs/dbt-core/issues/8606

Current the unit test spec is as follows:

```
unit:
  - model: my_model # name of the model I'm unit testing
    tests:
     - name: test_is_valid_email_address # this is the unique name of the test
       given: # optional: list of inputs to provide as fixtures
        - input: ref('users')
          rows:
           - {user_id: 1, email: cool@example.com,     email_top_level_domain: example.com}
           - {user_id: 2, email: cool@unknown.com,     email_top_level_domain: unknown.com}
           - {user_id: 3, email: badgmail.com,         email_top_level_domain: gmail.com}
           - {user_id: 4, email: missingdot@gmailcom,  email_top_level_domain: gmail.com}
         - input: ref('top_level_domains')
           rows:
            - {tld: example.com}
            - {tld: gmail.com}
       expect: # required: the expected output given the inputs above
        - {user_id: 1, is_valid_email_address: true}
        - {user_id: 2, is_valid_email_address: false}
        - {user_id: 3, is_valid_email_address: false}
        - {user_id: 4, is_valid_email_address: false}
    - name: test_another_column
      ...
```

we should adjust it so that the block is
1. named `unit-tests:` instead of `unit:`
2. starts with the test name instead of the model name

the final spec should look like this:

```
unit-tests:
  - name: test_is_valid_email_address # this is the unique name of the test
    model: my_model # name of the model I'm unit testing
    given: # optional: list of inputs to provide as fixtures
      - input: ref('users')
        rows:
         - {user_id: 1, email: cool@example.com,     email_top_level_domain: example.com}
         - {user_id: 2, email: cool@unknown.com,     email_top_level_domain: unknown.com}
         - {user_id: 3, email: badgmail.com,         email_top_level_domain: gmail.com}
         - {user_id: 4, email: missingdot@gmailcom,  email_top_level_domain: gmail.com}
      - input: ref('top_level_domains')
        rows:
         - {tld: example.com}
         - {tld: gmail.com}
    expect: # required: the expected output given the inputs above
      - {user_id: 1, is_valid_email_address: true}
      - {user_id: 2, is_valid_email_address: false}
      - {user_id: 3, is_valid_email_address: false}
      - {user_id: 4, is_valid_email_address: false}
  - name: test_another_column
    ...
```

### Acceptance criteria

- unit test block is called `unit-tests:`
- unit test block starts with test name (instead of model name)

### Impact to Other Teams

None

### Will backports be required?

No

### Context

_No response_

### LINKED ISSUE #8699: [Implementation] update config block names for data tests and unit tests
### Housekeeping

- [X] I am a maintainer of dbt-core

### Short description

From https://github.com/dbt-labs/dbt-core/issues/8606

We should updating the config names 
- from `unit:` -> `unit-tests:` 
- and `tests:` -> `data-tests:` (we should preserve `tests:` for backwards compatibility)

### Acceptance criteria

- config name for unit tests is `unit-tests:`
- config name for data tests is `data-tests:` or `tests:` (the latter for backwards compatibility)

### Impact to Other Teams

None

### Will backports be required?

None

### Context

_No response_

### PR DESCRIPTION
**Pull request by emmyoop**
resolves #8699

### Problem

With the addition of `unit_tests` the config for `tests` is confusing as it currently does not include unit_tests, only data_tests.

### Solution

Explicitly define data_tests as data_tests in both schema files and in `dbt_project.yml`.

Also updated `unit-tests` to be `unit_tests` in `dbt_project.yml` for consistency. 

Continue to support the `tests` config for backwards compatibility but add a deprecation warning for it.

### Checklist

- [ ] I have read [the contributing guide](https://github.com/dbt-labs/dbt-core/blob/main/CONTRIBUTING.md) and understand what's expected of me  
- [ ] I have run this code in development and it appears to resolve the stated issue  
- [ ] This PR includes tests, or tests are not required/relevant for this PR
- [ ] This PR has no interface changes (e.g. macros, cli, logs, json artifacts, config files, adapter interface, etc) or this PR has already received feedback and approval from Product or DX
- [ ] This PR includes [type annotations](https://docs.python.org/3/library/typing.html) for new and modified functions

### CODE REVIEW

**Comment by gshank** [comment]
@graciegoheen The ticket that's referenced is contradictory about whether the config key in yaml should be "data-tests" or "data_tests".  Which do you want in schema.yml?

**Comment by graciegoheen** [comment]
My understanding was that it had to have `_` in the schema yml files and `-` in the `dbt_project.yml` file (similar to how we handle semantic models - `semantic_models` in [schema yml](https://docs.getdbt.com/docs/build/semantic-models#semantic-models-components), `semantic-models` in [dbt_project.yml](https://docs.getdbt.com/reference/dbt_project.yml)). 

Let me know if that understanding was incorrect.

**Comment by emmyoop** [comment]
Using dash in the `dbt_project.yml` and underscore in the schema files is also the pattern used elsewhere.  `semantic-models` are another config we uses dashes in one place and underscores in another.  It was also decided to do this for `unit-tests` as implemented in #8988

**Review by gshank — APPROVED** [review]

**Comment by emmyoop** [comment]
@graciegoheen yes!  Underscored everywhere for `unit_tests` and `data_tests`!

Nothing else was modified that's called out in #9235.

**Pull request merged**
