### PR TITLE
group by column_name in accepted_values

### LINKED ISSUE #3905: accepted_values test doesn't work in all database engines
### Describe the bug
The `accepted_values` test produces SQL with `group by 1`. The group by index syntax is not ANSI SQL and not supported in all database engines. This should be avoided in shared code like tests.

### Steps To Reproduce
Put an `accepted_values` test in your code and connect to a MS SQL database.

### Expected behavior
Test checks for the values.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] other (specify: MS SQL)

**The output of `dbt --version`:**
```
dbt --version
installed version: 0.20.2
   latest version: 0.20.2

Up to date!

Plugins:
  - bigquery: 0.20.2
  - snowflake: 0.20.2
  - redshift: 0.20.2
  - postgres: 0.20.2
  - sqlserver: 0.20.1
  - synapse: 0.20.0
```

**The operating system you're using:** macOS

**The output of `python --version`:** Python 3.9.7

### PR DESCRIPTION
**Pull request by sdebruyn**
resolves #3905 

### Description
Group by index is not ANSI SQL and not supported in every database engine (e.g. MS SQL). Use group by column_name in shared code.

### Checklist

- [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
- [x] I have run this code in development and it appears to resolve the stated issue
- [x] This PR includes tests, or tests are not required/relevant for this PR
- [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by jtcohen6** [comment]
Closing and re-opening to trigger adapter integration tests. Assuming they all pass, we can sneak this in for v0.21.0-rc1.

**Comment by jtcohen6** [comment]
@sdebruyn Looks like I don't have permission to resolve changelog conflicts by pushing to your fork. If you can manage to do that in the next hour, we might just be able to get this in under the v0.21 wire. If not, this will have to wait for a future release.

**Comment by sdebruyn** [comment]
@jtcohen6 resolved :)

**Review by jtcohen6 — APPROVED** [review]

**Comment by swanderz** [comment]
@jtcohen6 any chance we could patch this change into `v0.20.0`? Without this change, the `accepted_values` test isn't usable for `dbt-sqlserver~=0.20.0`, and we're currently blocked from upgrading to `v0.21.0` due to https://github.com/dbt-msft/dbt-sqlserver/issues/164

**Pull request merged**
