### PR TITLE
#3682 Changed how tables and views are generated to be able to use differen…

### LINKED ISSUE #3682: BigQuery KMS should not be used on VIEWS
### Describe the bug
If I add one kms key for the entire project that should be used for all models, like below. It will blow up, because you can't add KMS encryption to views. ( Unless I'm missing something here )

```yml
models:
  test:
    +kms_key_name: 'projects/<project>/locations/<location>/keyRings/key-ring/cryptoKeys/key'
```

### Steps To Reproduce
Add kms_key_name to the entire project or specific folder that contains views.

### Expected behavior
It should skip views, and only add the encryption key to the tables.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
dbt --version
installed version: 0.20.0
   latest version: 0.20.0

Up to date!

Plugins:
  - bigquery: 0.20.0
  - snowflake: 0.20.0
  - redshift: 0.20.0
  - postgres: 0.20.0
```

**The operating system you're using:**
MAC

### Additional context
Should probably be in its own issue, but I would like to be able to add default encryption key to the entire dataset that DBT creates. Maybe this is possible, but I didn't find anything about it :)

Cheers!

### PR DESCRIPTION
**Pull request by AndreasTA-AW**
…t options

resolves #3682

### Description
I added a new function called common where common options can be put, otherwise views and tables are separated from each other to be able to add either for both or a single one of them.

Not sure if it's good enough or what you say. I ran the tests but didn't touch them.

### Checklist
 - [x] I have signed the [CLA](https://docs.getdbt.com/docs/contributor-license-agreements)
 - [x] I have run this code in development and it appears to resolve the stated issue
 - [x] This PR includes tests, or tests are not required/relevant for this PR
 - [x] I have updated the `CHANGELOG.md` and added information about my change to the "dbt next" section.

### CODE REVIEW

**Comment by AndreasTA-AW** [comment]
I'll ping here. Would be nice if someone looks at this. I will sign the agreement when we think this will eventually be merged :)

**Review by jtcohen6 — COMMENTED** [review]
Thanks for this @AndreasTA-AW! The code looks good to me. Appreciate the ping, and sorry for the delay getting back to you.

As far as testing this change, I think a unit test in the style of [these ones](https://github.com/dbt-labs/dbt/blob/9e796671dd55d4781284d36c035d1db19641cd80/test/unit/test_bigquery_adapter.py#L843-L869) should be sufficient. How about something like:
```python
    def test_table_kms_key_name(self):
        adapter = self.get_adapter('oauth')
        mock_config = create_autospec(
            RuntimeConfigObject)
        config={'kms_key_name': 'some_key'}
        mock_config.get.side_effect = lambda name: config.get(name)

        expected = {
            'kms_key_name': "'some_key'"
        }
        actual = adapter.get_table_options(mock_config, node={}, temporary=False)
        self.assertEqual(expected, actual)

        
    def test_view_kms_key_name(self):
        adapter = self.get_adapter('oauth')
        mock_config = create_autospec(
            RuntimeConfigObject)
        config={'kms_key_name': 'some_key'}
        mock_config.get.side_effect = lambda name: config.get(name)

        expected = {}
        actual = adapter.get_view_options(mock_config, node={})
        self.assertEqual(expected, actual)
```
After adding that test, could you:
- Pull changes from `develop`
- Add a changelog entry below `## dbt 0.21.0 (Release TBD)`
- Sign the CLA

**Comment by AndreasTA-AW** [comment]
The tests looks great to me, I'll add those and make sure they pass. I'll then finish the rest of the tasks you added.

Thanks for looking in to it!

**Comment by jtcohen6** [comment]
@AndreasTA-AW Will you be able to sign the CLA? The PR looks in good shape, so that's the only blocker to merging this in.

**Comment by AndreasTA-AW** [comment]
Hi!
I'm actually waiting to get a GO on that, hopefully it will be solved anytime.

**Comment by AndreasTA-AW** [comment]
@jtcohen6 Sorry for the delay, I got an OK to sign it now, so it should all be fixed.

**Review by jtcohen6 — APPROVED** [review]
Thanks for the contribution @AndreasTA-AW!

**Pull request merged**
